### ISSUE TITLE
"genmove" with no color results in crash

### ISSUE THREAD

**Issue by sethtroisi** [tensorflow/minigo#204]
expected behavior not a crash

**Comment by amj** [comment]
is the crash in gtp.py?

**Comment by sethtroisi** [comment]
In may have been on this line https://github.com/jtauber/gtp/blob/master/gtp.py#L69 but minigo is complicated to setup so I can't verify

**Comment by tommadams** [comment]
I'll take this, I'm looking at that code anyway

**Comment by tommadams** [comment]
The problem is that gtp.py always assumes that the color is specified: https://github.com/jtauber/gtp/blob/1e55c3e0f146baf511264b8fa6294786c402dfff/gtp.py#L220

I'll just work around it for now because I'm going to refactor all that code soon and I'm not sure that gtp.Engine is actually giving us much benefit these days.
