### ISSUE TITLE
Add a Test to verify that c++ and python code produce identical games

### ISSUE THREAD

**Issue by sethtroisi** [tensorflow/minigo#300]
As I modify either engine it would be nice to trust that my changes are identical in both languages

**Comment by amj** [comment]
since the two random implementations are different, the only way to do this is to not use d-noise, softpick, or rotations.  There's flags to turn those all off for the cc code, i'm not sure if we put them behind flags for the python version.

**Comment by sethtroisi** [comment]
Alternatively we could have a very simple deterministic random sequence that both engines implement so that we don't have to turn off randomness.

**Comment by tommadams** [comment]
The Python code doesn't actually have flags to turn off all sources of random play; you have to change a couple of lines of code.

I agree that the best way forward is using the same RNG between both implementations, I regret not doing that at the time I wrote the C++ port. My choice would be [PCG random](www.pcg-random.org), it's high quality and simple to implement. I'd prefer to do this after we've landed the initial cloud TPU support next week, to save me some merge conflicts :)

**Comment by tommadams** [comment]
Good news! It looks Numpy random uses the 32bit Mersenne Twister and calls it twice to generate each 64bit random sample. Wrapping the 32bit std::mt19937 in a class that conforms to [UniformRandomBitGenerator](https://en.cppreference.com/w/cpp/named_req/UniformRandomBitGenerator)

**Comment by tommadams** [comment]
Update: I have a change

**Comment by tommadams** [comment]
With some effort, I got the Python and C++ code generating the exact same sequences of random numbers & Dirichlet distributions. It turns out though that TensorFlow inference will return slightly different results if the model is initialized from Python code directly or from a frozen GraphDef proto. Which is sad. The difference is < 0.1% but it's enough to cause the reads to quickly diverge, and the moves played to diverge after around move 20. We could change the Python code to round-trip the model through a frozen GraphDef but at this point it's probably not worth the effort.

The tree search code isn't under much active development these days and this investigation was enough to confirm that both the Python and C++ tree search behave the same.
