### ISSUE TITLE
cc/mcts_node.h child_U is dead code

### ISSUE THREAD

**Issue by amj** [tensorflow/minigo#353]
looks like with the new re-weighting, `node.child_U()` is only used in printing node statistics, which makes it a little misleading (as it's not actually the `U` used in calculations)

**Comment by tommadams** [comment]
Do you mean the zeroing out of illegal moves in #299? I didn't think that invalidated `child_U`.

As far as I can see, both [`child_U`](https://github.com/tensorflow/minigo/blob/27fd8e19e59fb73dcb7da6ac4d45eaa5c9d2c50c/cc/mcts_node.h#L67) and [`CalculateChildActionScore`](https://github.com/tensorflow/minigo/blob/27fd8e19e59fb73dcb7da6ac4d45eaa5c9d2c50c/cc/mcts_node.cc#L293) calculate U the same way (the only reason that `CalculateChildActionScore` doesn't call `child_U` is so that it can hoist the `sqrt(1+N)` call out of the loop).

Am I missing something?

**Comment by amj** [comment]
yeah i can't read :(
