### ISSUE TITLE
Minigo env for reinforcement learning

### ISSUE THREAD

**Issue by IsmailMamoru** [tensorflow/minigo#422]
Hello everyone,

Thank to the help of many of you, i was able to run the training using the data provided gs://$BUCKET_NAME/data (this is supervised learning)

However, is it possible to interact with the environment during the training?
Which means playing games real-time games and learning from them, not using the provided data.

Thank you

**Comment by tommadams** [comment]
You can load any of the training chunks as a model into the Python engine, e.g. `--model=gs://$BUCKET_NAME/$CHECKPOINT_DIR/model.ckpt-99918`

If you want to play using the C++ engine, the training checkpoint will have to be frozen first.

**Comment by IsmailMamoru** [comment]
thank you @tommadams ,that point is clear for me.
My question is : is it possible to play real-time games for reinforcement learning purposes an not train from games already played?
Thank you

**Comment by amj** [comment]
@IsmailMamoru i'm not sure what that means; the games cannot be "learned from" until they have finished and the result of the game is known -- otherwise, what would the value-head attempt to learn?

I'm pretty sure the answer to your question is "no", but please re-open if i'm misunderstanding your question.
