### ISSUE TITLE
Why is BOARD_SIZE still passed as an environment variable and not a parameter?

### ISSUE THREAD

**Issue by sethtroisi** [tensorflow/minigo#444]
It seems to be the only such parameter.

**Comment by amj** [comment]
In python?  Because of stuff that's set up at the first `import go` line.
In C++?  Because it's a build-time flag.

**Comment by tommadams** [comment]
For C++, I wanted the board size to be a compile time constant so we could used std::array for the board state, features, etc. This may have been a little overzealous.

For Python, I believe the issue is that go.N [gets initialized on module import](https://github.com/tensorflow/minigo/blob/53a354d1e0b3c296c8e8f207a10052bd18d1fb86/go.py#L31), which is most likely before the command line flags have been parsed. I guess we could make the board size a command line flag 
if we added extra argument parsing to go.py.

Opinions?

**Comment by amj** [comment]
The compile time constant seems fine for c++, although it means we have the weirdness that some tests run only on 9x9 and some don't.

For python, it seems fine to make go.py parse absl.flags.  Also we should make the default 19 :)

**Comment by tommadams** [comment]
You don't need to make the dependents of go.N lazy or use absl.flags. Something like the following, while kinda terrible, would work:
```python
parser = argparse.ArgumentParser()
parser.add_argument('--board_size', type=int, default=19)
N = parser.parse_known_args()[0].board_size
```

**Comment by sethtroisi** [comment]
These arguments make a moderate amount of sense. I guess it will be left as an oddity.
