### ISSUE TITLE
mismatch between the current graph and the graph from the checkpoint

### ISSUE THREAD

**Issue by chunmwan** [tensorflow/minigo#685]
when I tried ti run selfplay under win10 like below:
(tensorflow) C:\Users\chunmwan\Downloads\minigo>python selfplay.py --verbose=2 --num_readouts=400 --load_file c:\Users\chunmwan\Downloads\minigo\models\000798-golden-lion
got below error:
  File "C:\Users\chunmwan\Downloads\minigo\dual_net.py", line 165, in initialize_weights
    tf.train.Saver().restore(self.sess, save_file)
  File "C:\Users\chunmwan\AppData\Local\conda\conda\envs\tensorflow\lib\site-packages\tensorflow\python\training\saver.py", line 1582, in restore
    err, "a mismatch between the current graph and the graph")
tensorflow.python.framework.errors_impl.InvalidArgumentError: Restoring from checkpoint failed. This is most likely due to a mismatch between the current graph and the graph from the checkpoint. Please ensure that you have not altered the graph expected based on the checkpoint. Original error:

Assign requires shapes of both tensors to match. lhs shape= [32] rhs shape= [256]
         [[node save/Assign_3 (defined at C:\Users\chunmwan\Downloads\minigo\dual_net.py:165)  = Assign[T=DT_FLOAT, _class=["loc:@batch_normalization/gamma"], use_locking=true, validate_shape=true, _device="/job:localhost/replica:0/task:0/device:CPU:0"](batch_normalization/gamma/Momentum, save/RestoreV2:3)]]

**Comment by amj** [comment]
try setting the environment variable BOARD_SIZE=19, or passing the flag --board_size=19.

(@brilee is there a reason for us to default to 9x9 anymore?  I think we maybe should switch the default)

**Comment by brilee** [comment]
Yeah, seems reasonable to update the defaults to whatever net size we're publishing.

**Comment by sangurocactus** [comment]
I got the same error message when training a BERT model. I passed the flag--board-size=19 but it didn't help. Any guidance on how to resolve the issue is most appreciated.  Below is a snippet of the error message:

E0722 20:47:39.150068 140097652520704 error_handling.py:70] Error recorded from training_loop: Restoring from checkpoint failed. This is most likely due to a mismatch between the current graph and the graph from the checkpoint. Please ensure that you have not altered the graph expected based on the checkpoint. Original error:

Assign requires shapes of both tensors to match. lhs shape= [28996,768] rhs shape= [30522,768]
         [[node save/Assign_13 (defined at ./bert/run_classifier.py:880) ]]

Errors may have originated from an input operation.
Input Source operations connected to node save/Assign_13:
 bert/embeddings/word_embeddings/adam_m (defined at /home/wang_/bert/optimization.py:122)

**Comment by brilee** [comment]
You don't appear to be doing anything with Minigo - looks like a general error with how you're calling your code, but I can't help you any more than that.

**Comment by amj** [comment]
@sangurocactus the clue here for us is the paths: "bert/embeddings/word_embeddings/adam_m (defined at /home/wang_/bert/optimization.py:122)"

We're not related to embeddings, words, or the adam optimizer, nor do we have an 'optimization.py' file.
