### ISSUE TITLE
is the standard of choose opponent reasonable

### ISSUE THREAD

**Issue by l1t1** [tensorflow/minigo#695]
https://cloudygo.com/v16-19x19/eval-model/986?sorted=False

**Comment by amj** [comment]
yes; you can change "sorted=True" in the URL, or you can click "toggle sort" at the top of the first column.

Also, cloudygo.com is run by @sethtroisi , at github.com/sethtroisi/cloudygo -- cloudygo issues can be reported there :)

**Comment by l1t1** [comment]
eg, we choose opponents from the list of

Ratings from	105917 games	rating	uncertainty
Best model	000930-goliath	4451	± 25
2	000894-affray	4391	± 22
3	000984-prospero	4355	± 32
4	000805-pallas	4341	± 20
5	000882-glory	4339	± 21
6	000942-duchess	4331	± 23
7	000899-kingfisher	4319	± 22
8	000959-phoenix	4300	± 25
9	000833-black-prince	4298	± 21
10	000905-hydra	4297	± 23
11	000960-conqueror	4293	± 28
12	000938-hercules	4292	± 30
13	000965-coronation	4274	± 39
14	000883-acheron	4273	± 23
15	000892-alliance	4272	± 24

instead of

921,931~971

**Comment by l1t1** [comment]
thanks

**Comment by amj** [comment]
are you asking about how we display the games (in which case, there's the toggle in the table header), or are you asking how we choose the matches?

Because we currently match them against the recent models, but we also play matches among top models and among the models that have the 'most uncertain' rating.
