### ISSUE TITLE
could you publish the elo of v17

### ISSUE THREAD

**Issue by l1t1** [tensorflow/minigo#722]
about 10M games played

**Comment by sethtroisi** [comment]
We're still waiting on building a new docker evaluator image, I'll publish our normal stats after that.

**Comment by l1t1** [comment]
could you convert some v17 weights to lz format and give the download link?

**Comment by sethtroisi** [comment]
unfortunately we can't. LZ doesn't support Squeeze and Excitation that we added in v17.

**Comment by chunmwan** [comment]
could you provide how to play minigo in sabaki with v17 weights?

**Comment by l1t1** [comment]
what is the train result of v17?

**Comment by l1t1** [comment]
it seems the training paused 
1003  001003-leviathan  2019-02-25 20:16 
1 days 3.8 hours ago 
262922

**Comment by l1t1** [comment]
from https://cloudygo.com/v17-19x19/eval-graphs
,it seems training made very small progress
Ratings from 5840 games rating uncertainty 
Best model 000605-invincible  3871 ± 190 
2 000353-orpheus  3807 ± 170 
3 000284-temeraire  3788 ± 231 
4 000848-europa  3777 ± 228

**Comment by sethtroisi** [comment]
if you look each of the models has only played a couple of other models.
Andrew is playing all the eval games right now but it will take a couple of days.

**Comment by l1t1** [comment]
i see, could you set a match vs v15  weight?

Ratings from	11517 games	rating	uncertainty
Best model	000913-swift	4792	± 191
2	000848-europa	4764	± 163
3	000803-tiger	4749	± 177

**Comment by amj** [comment]
I promise you, we will play cross-run matches as soon as we have an idea what the best v17 models are.

Looking at the top models
913 has played 1 opponent
848 has played 3 opponents
803 has played 4.

Please be patient :)

**Comment by WhiteHalmos** [comment]
Thank you for setting up and running all these eval games!

The one I appreciate the most is https://cloudygo.com/all-eval-graphs?bucket=cross-run-eval (maybe I should make a PR to add a link to it 😛 ). Makes progress (or not) very clear.

**Comment by sethtroisi** [comment]
@WhiteHalmos I'd love a pull request (or even filling an issue so that I remember to add the link).

One of the reason the all-eval-graph has been slow is Andrew and I are rethinking how to do cross evals. The old ["all-eval-graph"](https://cloudygo.com/all-eval-graphs?bucket=cross-asdf) has 1.1 MILLION GAMES! and still doesn't distill out the appropriate knowledge.

If you were interested in helping or providing some ideas we'd also value that otherwise Andrew and I will probably need to one or two more iterations on our current idea.

The current approach is something like
  * Pick a hundred good models for each run ([Code](https://github.com/sethtroisi/minigo/blob/cross_eval_pairer/oneoffs/cross_eval_models.py))
    * We pick 75 models spaced evenly over the curve + 25 top models for runs that are complete
    * What to do with ongoing runs?
  * Now that we have 7 runs x 100 models play games between models of "same" strength ([Code](https://github.com/sethtroisi/minigo/blob/cross_eval_pairer/cluster/evaluator/launch_eval.py))
    * How to do with weird games like [this](https://cloudygo.com/cross-run-eval/10124/eval/2019-02-07/1549545309-minigo-cc-evaluator-v15-553-vs-v16-16-bw-c4fgj-0-000016-hazardous-000553-duke.sgf?type=eval)
    * How to make sure that all games get reasonable number of pairings?
    * Should we allow inter run games...

**Comment by l1t1** [comment]
if training all weights without testing their strength at the same time,how to make sure they make progress, and how to know when should stop the training

**Comment by WhiteHalmos** [comment]
@sethtroisi Created an issue.

For cross evals, is equal-playout the desired method? I think equal-time comparison is gated on containerization?

What do you think about rather than picking a fixed number of good models from each run, just pick every 10th model (or equivalently, one out of every 10 consecutive models)? This would average out to about 100 evenly spaced out models per run, and also a higher likelihood of being able to reuse some eval games between those models (since they're closer together). There likely won't be many games between most of these models from the same run since they're too far apart.

For completed runs, I would think just the top 10 models would be fine, since the evenly spaced out models already give a really good idea of the general trend of the training.

As to additional games, what do you think about just using the same eval pairing logic for inter-run games? i.e. treat these 7x100+ models as being from the same run and pair the ones that would increase rating confidence.

**Comment by l1t1** [comment]
why the elo scores of most weights became higher and higher, mucher higher than v15 or v16?

**Comment by amj** [comment]
@WhiteHalmos equal-time would be a preferable way to compare but there are some difficulties: For very short time setting, any neighbor-process contention or whatever can really skew the results.  We observed this informally when running equal-time games on local machines -- even small blips in something else contending for the GPU are enough to really sabotage one side or the other.

I agree with the idea of using the same pairing logic for inter-run games :)

@l1t1 probably because it hasn't played all the pairings yet.

**Comment by l1t1** [comment]
Best model 000997-golden-phoenix  7067 ± 29 
2 000961-artemis  7066 ± 29 
3 001003-leviathan  7066 ± 28 
4 000881-bulldog  7062 ± 30 

I think the score is abnormal

**Comment by l1t1** [comment]
https://cloudygo.com/all-eval-graphs?bucket=cross-run-eval
is more reasonable
Best model v17-19x19/000961-artemis  3102 ± 46 
2 v16-19x19/000894-affray  3045 ± 25 
3 v16-19x19/000930-goliath  3042 ± 25 
4 v17-19x19/000997-golden-phoenix  3041 ± 45 
5 v17-19x19/000907-lincoln  3037 ± 50

**Comment by l1t1** [comment]
what is the final result of train v17?

**Comment by sethtroisi** [comment]
Final results for v17 are here:
https://cloudygo.com/v17-19x19/eval-graphs
and some games vs LZ
https://cloudygo.com/ringmaster/v17-minigo-v-leela-1.report/
