### ISSUE TITLE
Is Minigo officially stronger than LZ at this point?

### ISSUE THREAD

**Issue by hydrogenpi** [tensorflow/minigo#723]
I don't see it anywhere published on this or the leela zero place. but guys on the Life in 19 by 19 are saying that Minigo latest is much stronger than and in fact is up to par with the ELF latest if not even better.

If Minigo is indeed stronger than Leela Zero now, is there an adapted version that is LZ format ready that can be used inside of Lizzie?

**Comment by bvandenbon** [comment]
I have the exact same questions. The commands don't even have to be exactly the same, but it would be nice if you could tell us the equivalent of LZ's "lz-analyze" GTP command for example, which prints statistics about candidate moves at fixed intervals.

That would allow us to make Lizzie compatible with minigo.

**Comment by sethtroisi** [comment]
@bvandenbon you should checkout [MiniGui](https://github.com/tensorflow/minigo/tree/master/minigui), which has study and eval code.

**Comment by amj** [comment]
@bvandenbon we provide statistics about candidate moves in fixed intervals over stderr, which we've written about and think is the correct approach.  Certainly a gtp command to echo them to stdout would be an ok workaround but otherwise i think there's a good reason to not make UI gtp-extensions on the engines themselves.  

Feel free to reopen this (or open another issue) if you'd like to suggest another approach :)
