### ISSUE TITLE
[ml_perf]eval failed bacause double pass

### ISSUE THREAD

**Issue by delock** [tensorflow/minigo#751]
I met this error when running one of the eval games
```
[F] game.cc:88 : check failed: !game_over_                                   
                                                                             
  0x41a127  minigo::Game::SetGameOverBecauseOfPasses()                       
  0x417404  minigo::MctsPlayer::PlayMove()                                   
  0x409d0a  minigo::(anonymous namespace)::Evaluator::ThreadRun()            
  0x7f65f80f4ad0  execute_native_thread_routine                              
```
Some debugging shows that game_over condition had not been checked between two moves:
https://github.com/tensorflow/minigo/blob/master/cc/eval.cc#L205
```
      curr_player->PlayMove(move);
      next_player->PlayMove(move);
```
It should be changed to the following and the game can finish normally.
```
      curr_player->PlayMove(move);
      if (game.game_over()) {
        break;
      }
      next_player->PlayMove(move);
```

**Comment by tommadams** [comment]
Sorry, looks like I broken that with PR #744 attempting to fix a different crash.

This mess stems from the fact that historically Minigo has not an object whose sole responsibility was to track the game state, and I introduced the `Game` class only fairly recently and it was a somewhat awkward fit.

As suggested in the comments of #744 I think there's a better architecture that would avoid these kinds of problems:

- The players register themselves with the game object.
- The current player suggests the next move via `MctsPlayer::SuggestMove` (no change).
- The move is played on the `Game` object rather than directly on the players:
  - `Game` calls `PlayMove` on the registered players (one in the case of selfplay, two in the case of eval). This removes the need for duplicate move handling.
  - `Game` performs game over state checking not the `MctsPlayer`, avoiding the but here.

I'll have to have a think about priorities and figure out if we have time to make such a change before the the fast approaching date by which the reference implementation has to be finished for MLPerf :)
