### ISSUE TITLE
Looking for an automatic process of doing multiple iterations of reinforcement learning

### ISSUE THREAD

**Issue by iaxax** [tensorflow/minigo#823]
Hi, the README.md only tells us how to do one iteration of reinforcement learning on 9x9. But I wonder if we can do the selfplay-training loop as many times as we wish. Does such script exist? Or do I misunderstand something?

Thanks!:)

**Comment by tommadams** [comment]
Our full reinforcement learning loop runs on a Kubernetes cluster, since training a model on a single machine is rather slow. There are some instructions here: https://github.com/tensorflow/minigo/tree/master/cluster

We do have a couple of references for running the full loop on a single machine, however.

[rl_loop/local_integration_test.py](https://github.com/tensorflow/minigo/blob/master/rl_loop/local_integration_test.py) runs a single full iteration of the RL loop, though it only plays a very small number of selfplay games. In reality, you'll want to play several thousand. This plays using our Python engine, so it will be rather slow to play the required number of games.

[ml_perf/reference_implementation.py](https://github.com/tensorflow/minigo/blob/master/ml_perf/reference_implementation.py) trains a 9x9 model to beat a target model. This uses the C++ engine and so can play thousands of games in parallel for better throughput. We chose the hyperparameters for this script that trains a model quickly, but this results in a model whose value head is somewhat over-fit. It still plays a recognizable game of Go though! If you get this working, we can talk about how to tweak the script to avoid over-fitting.

Hopefully that's enough to get you started.

**Comment by iaxax** [comment]
That helps me a lot!

And I have two more questions.
(1) Why is training loop in [ml_perf/reference_implementation.py](https://github.com/tensorflow/minigo/blob/master/ml_perf/reference_implementation.py) over-fit?
Is it because of biased sampling of training data as you mentioned in the code?
(2) Does the training loop on a Kubernetes cluster work exactly as rl_loop does in [ml_perf/reference_implementation.py](https://github.com/tensorflow/minigo/blob/master/ml_perf/reference_implementation.py) except the over-fit part?

Actually, I'm not going to train an effective model on my machine. I'm just curious about how to do such training from scratch.

Really appreciate for your patience:)

**Comment by tommadams** [comment]
(Sorry for any typos, I'm on vacation and typing this on my phone.)

The model is over fit because the selfplay stage doesn't play enough games
each iteration of the loop and we sample too many positions from each game
during training. If you look at ml_perf/flags/9/train.flags you can see the
filter amount is set to 0.5, so we sample 50% of the moves from each game.
Since positions from one game all look similar to each other, training will
over fit to these game.

A better approach (which we use for our full training pipeline) is to play
something like 10x the number of games and only sample 5% of the positions
from each game, which increases the diversity of positions seen during
training and reduces over fitting. The training loop randomly samples games
from the previous 20 iterations of self play, so sampling 5% will sample
every position on average once.

This approach obviously takes a lot more CPU, which prohibits training a
model from scratch on a single machine in less than a week using the
AlphaGo Zero algorithm.

The code to train on Kubernetes has a few differences, the most important
two are:

1) Training and self play run in parallel: training always samples from a
sliding window of the most recently payed games & self play always used the
most recently trained model to play moves.

2) Kubernetes training doesn't play evaluation games to check that the new
model is better than the previous one: whenever a new model is trained, we
immediately start using it to play games.

**Comment by tommadams** [comment]
Ugh, looks like replying from my phone lost all my formatting, sorry about
that! Hopefully it makes sense.

**Comment by iaxax** [comment]
Got it. By the way, have fun on your vacation!

**Comment by amj** [comment]
@iaxax closing as answered.  Feel free to reopen if needed :)
