### ISSUE TITLE
Hyperparameters

### ISSUE THREAD

**Issue by sherdencooper** [tensorflow/minigo#892]
Hi, I am studying Alphazero/Alphago zero and this repo is really helpful! According to the paper about Alphago zero, the hyperparameters are tuned by **_Bayesian optimization_**. I wonder if you use such strategy in minigo to select hyperparameters or reuse the hypermeters from other places?

**Thanks a lot in advance!**

**Comment by amj** [comment]
It depends on the parameters you're talking about:  Our first choice was to use the parameters as published in deepmind's papers, which said they used bayesian optimization.  If you have questions about specific parameters not in DM's papers, happy to answer but otherwise i'd check their paper first :)

**Comment by sethtroisi** [comment]
Adding to Andrew's comments, we've optimizing a handful of the parameters (cpuct, num_readouts, num_virtual_losses, learning_rate, l2_cost) independently at various points but not holistically or during a RL run.
